import { EmailItem, InboxStats } from '../types/email';

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400 * 1000).toISOString();

export const MOCK_EMAILS: EmailItem[] = [
  {
    emailId: 'val-001-sched',
    threadId: 'thread-101',
    sender: 'alex.rivers@acmecorp.com',
    subject: 'Q3 Partnership Strategy Sync & Pitch Deck',
    receivedAt: hoursAgo(1),
    readStatus: 'read',
    isNoReply: false,
    noReplyReason: null,
    importanceScore: 94.5,
    importanceLevel: 'urgent',
    importanceJustification: 'VIP Partner executive; contains direct time-sensitive meeting request with key deliverables before end of week.',
    summary: 'Alex is requesting a 45-minute sync to finalize the Q3 partnership terms and review the updated pitch deck before Friday\'s board review.',
    isSchedulingRelated: true,
    hasCalendarContext: true,
    calendarContext: {
      rangeStart: now.toISOString(),
      rangeEnd: new Date(now.getTime() + 7 * 86400 * 1000).toISOString(),
      busyBlocks: [
        {
          start: new Date(now.getTime() + 18 * 3600 * 1000).toISOString(),
          end: new Date(now.getTime() + 19.5 * 3600 * 1000).toISOString(),
        },
        {
          start: new Date(now.getTime() + 42 * 3600 * 1000).toISOString(),
          end: new Date(now.getTime() + 43.5 * 3600 * 1000).toISOString(),
        }
      ],
      suggestedSlots: [
        {
          start: new Date(new Date().setHours(14, 0, 0, 0) + 86400000).toISOString(), // Tomorrow 2:00 PM
          end: new Date(new Date().setHours(14, 45, 0, 0) + 86400000).toISOString(),
        },
        {
          start: new Date(new Date().setHours(10, 30, 0, 0) + 2 * 86400000).toISOString(), // In 2 days 10:30 AM
          end: new Date(new Date().setHours(11, 15, 0, 0) + 2 * 86400000).toISOString(),
        },
        {
          start: new Date(new Date().setHours(16, 0, 0, 0) + 2 * 86400000).toISOString(), // In 2 days 4:00 PM
          end: new Date(new Date().setHours(16, 45, 0, 0) + 2 * 86400000).toISOString(),
        }
      ],
      eventCount: 4,
      events: [
        {
          summary: 'Internal Team Standup',
          start: new Date(new Date().setHours(9, 0, 0, 0) + 86400000).toISOString(),
          end: new Date(new Date().setHours(9, 30, 0, 0) + 86400000).toISOString(),
          allDay: false,
        },
        {
          summary: 'Product Roadmap Review',
          start: new Date(new Date().setHours(11, 0, 0, 0) + 86400000).toISOString(),
          end: new Date(new Date().setHours(12, 0, 0, 0) + 86400000).toISOString(),
          allDay: false,
        }
      ],
      generatedAt: hoursAgo(1),
    },
    replyOutline: [
      'Acknowledge enthusiasm for the Q3 partnership milestone and draft terms',
      'Confirm availability for Tomorrow at 2:00 PM - 2:45 PM or Thursday at 10:30 AM (cross-checked with Google Calendar)',
      'Request the updated pitch deck v3 link beforehand to prepare feedback notes',
      'Offer to bring our Technical Lead onto the call if architecture questions arise',
    ],
    replyOutlineStatus: 'suggested',
    outlineEligible: true,
    processedAt: hoursAgo(1),
    body: `Hi Team,\n\nHope your week is off to a great start! We've made substantial revisions to the Q3 partnership proposal and the accompanying pitch deck after our board feedback.\n\nCould we jump on a 45-minute call sometime over the next two days to align on the core terms and finalize the launch schedule? Let me know what times work best for your calendar.\n\nBest regards,\nAlex Rivers\nVP Strategic Growth, Acme Corp`,
    isStale: false,
  },
  {
    emailId: 'val-002-urgent',
    threadId: 'thread-102',
    sender: 'elena.rostova@cloudscale.io',
    subject: 'URGENT: Production API Gateway Latency Spike & Failover',
    receivedAt: hoursAgo(2),
    readStatus: 'read',
    isNoReply: false,
    noReplyReason: null,
    importanceScore: 98.2,
    importanceLevel: 'urgent',
    importanceJustification: 'Critical infrastructure alert; urgent tone keywords detected from primary technical lead.',
    summary: 'Elena reports a 300ms latency spike in the US-East API Gateway clusters and asks for approval to initiate region failover routing.',
    isSchedulingRelated: false,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: [
      'Acknowledge critical incident status immediately',
      'Approve emergency traffic rerouting to US-Central failover cluster',
      'Request real-time status updates in the #prod-incident War Room channel',
      'Instruct team to preserve telemetry logs for post-mortem root cause analysis',
    ],
    replyOutlineStatus: 'edited',
    outlineEligible: true,
    processedAt: hoursAgo(2),
    body: `Team,\n\nWe are currently seeing an unexpected 300ms p99 latency surge across the US-East primary gateway nodes following the latest upstream deployment.\n\nIf error rates exceed 1.5%, we recommend initiating immediate failover to the standby US-Central cluster. Please confirm if you authorize the routing transition.\n\nElena Rostova\nLead SRE`,
    isStale: false,
  },
  {
    emailId: 'val-003-unread',
    threadId: 'thread-103',
    sender: 'marcus.vance@investor-partners.vc',
    subject: 'Follow-up on Seed Round Term Sheet & Valuation Cap',
    receivedAt: hoursAgo(3),
    readStatus: 'unread',
    isNoReply: false,
    noReplyReason: null,
    importanceScore: 88.0,
    importanceLevel: 'high',
    importanceJustification: 'Investor correspondent; discusses funding round terms and cap table details.',
    summary: 'Marcus sends comments regarding the valuation cap and requested board observer seats for the upcoming financing round.',
    isSchedulingRelated: false,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: null,
    replyOutlineStatus: 'none',
    outlineEligible: false,
    processedAt: hoursAgo(3),
    body: `Hello,\n\nOur investment committee met yesterday to review the proposed term sheet revisions. We are aligned on the valuation cap and standard pro-rata rights, with one clarifying question on the board observer seat allocation.\n\nPlease take a look at the redline attached when you have a moment.\n\nWarmly,\nMarcus Vance`,
    isStale: false,
  },
  {
    emailId: 'val-004-noreply',
    threadId: 'thread-104',
    sender: 'notifications@github.com',
    subject: '[valence-ai/core] Security advisory: High severity dependency vulnerability',
    receivedAt: hoursAgo(4),
    readStatus: 'read',
    isNoReply: true,
    noReplyReason: 'Sender matches automated system pattern (notifications@); Auto-Submitted: auto-generated header present.',
    importanceScore: 45.0,
    importanceLevel: 'medium',
    importanceJustification: 'Automated GitHub security alert regarding repository dependencies.',
    summary: 'Dependabot alert flagged CVE-2026-38291 in package axios requiring upgrade to v1.9.0.',
    isSchedulingRelated: false,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: null,
    replyOutlineStatus: 'not_applicable',
    outlineEligible: false,
    processedAt: hoursAgo(4),
    body: `Dependabot detected 1 high severity vulnerability in package axios.\n\nVulnerability: ReDoS via malformed URL query params (CVE-2026-38291).\nRemediation: Upgrade axios to version >= 1.9.0.\n\nView details: https://github.com/valence-ai/core/security/dependabot/12`,
    isStale: false,
  },
  {
    emailId: 'val-005-stale',
    threadId: 'thread-101',
    sender: 'alex.rivers@acmecorp.com',
    subject: 'Re: Q3 Partnership Strategy Sync & Pitch Deck',
    receivedAt: hoursAgo(6),
    readStatus: 'read',
    isNoReply: false,
    noReplyReason: null,
    importanceScore: 82.0,
    importanceLevel: 'high',
    importanceJustification: 'Prior thread message superseded by newer email from the same sender.',
    summary: 'Earlier initial note from Alex asking if we have bandwidth for Q3 planning this month.',
    isSchedulingRelated: false,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: [
      'Confirm willingness to connect on Q3 planning',
      'Mention that calendar details will follow',
    ],
    replyOutlineStatus: 'suggested',
    outlineEligible: true,
    processedAt: hoursAgo(6),
    body: `Hey there, just touching base to see if we can get preliminary thoughts on the Q3 partnership before we draft the deck?`,
    isStale: true,
  },
  {
    emailId: 'val-006-team',
    threadId: 'thread-106',
    sender: 'clara.zhao@designstudio.co',
    subject: 'Updated Valence UI Design System & Component Library (Figma)',
    receivedAt: hoursAgo(8),
    readStatus: 'read',
    isNoReply: false,
    noReplyReason: null,
    importanceScore: 76.0,
    importanceLevel: 'high',
    importanceJustification: 'Design contractor deliverable; contains Figma tokens and handoff assets.',
    summary: 'Clara has published the new high-contrast blue, white, and black theme specs and components in Figma for developer review.',
    isSchedulingRelated: false,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: [
      'Thank Clara for delivering the UI design system updates ahead of schedule',
      'Confirm the engineering team has integrated the color tokens and typography scale',
      'Ask for clarification on the active hover glow states for dark-mode cards',
    ],
    replyOutlineStatus: 'suggested',
    outlineEligible: true,
    processedAt: hoursAgo(8),
    body: `Hey,\n\nThe new Valence dark/light theme system is ready in Figma! We've refined the blue accent shades (#2563EB, #3B82F6, #60A5FA) with deep obsidian backgrounds and crisp white typography.\n\nLet me know if you need any SVGs or token exports exported directly.\n\nClara`,
    isStale: false,
  },
  {
    emailId: 'val-007-billing',
    threadId: 'thread-107',
    sender: 'billing@anthropic.com',
    subject: 'Your Claude API Invoice #INV-2026-08 is now available',
    receivedAt: daysAgo(1),
    readStatus: 'read',
    isNoReply: true,
    noReplyReason: 'Transactional finance billing address; List-Unsubscribe header present; no user response required.',
    importanceScore: 30.0,
    importanceLevel: 'low',
    importanceJustification: 'Automated invoice receipt.',
    summary: 'Monthly Claude API usage invoice receipt for $428.50 automatically charged to payment method ending in 4092.',
    isSchedulingRelated: false,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: null,
    replyOutlineStatus: 'not_applicable',
    outlineEligible: false,
    processedAt: daysAgo(1),
    body: `Thank you for your business. Your monthly invoice for Claude API usage is $428.50. This amount has been charged to your card ending in 4092. You can download the PDF receipt in the Anthropic Console.`,
    isStale: false,
  },
  {
    emailId: 'val-008-coffee',
    threadId: 'thread-108',
    sender: 'david.kim@stanford.edu',
    subject: 'Catching up at NeurIPS / Bay Area coffee next week?',
    receivedAt: daysAgo(1),
    readStatus: 'unread',
    isNoReply: false,
    noReplyReason: null,
    importanceScore: 68.0,
    importanceLevel: 'medium',
    importanceJustification: 'Academic / alumni contact; casual scheduling inquiry.',
    summary: 'David asks if you are in SF next Tuesday or Wednesday afternoon for a quick coffee catchup on AI agent research.',
    isSchedulingRelated: true,
    hasCalendarContext: false,
    calendarContext: null,
    replyOutline: null,
    replyOutlineStatus: 'none',
    outlineEligible: false,
    processedAt: daysAgo(1),
    body: `Hey! Hope everything is going great with the new startup. I will be in Palo Alto and downtown SF for a couple of days next week. Any chance you have 30 mins open for a coffee chat on Tuesday or Wednesday?\n\nBest,\nDavid`,
    isStale: false,
  }
];

export const MOCK_STATS: InboxStats = {
  total: 8,
  unread: 2,
  noReply: 2,
  scheduling: 2,
  withOutline: 4,
  unprocessed: 0,
  byLevel: {
    urgent: 2,
    high: 3,
    medium: 2,
    low: 1,
  },
};
